export const AUTHOR_LIST_REQUEST = 'AUTHOR_LIST_REQUEST'
export const AUTHOR_LIST_SUCCESS = 'AUTHOR_LIST_SUCCESS'
export const AUTHOR_LIST_ERROR = 'AUTHOR_LIST_ERROR'

export const POST_LIST_REQUEST = 'POST_LIST_REQUEST'
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS'
export const POST_LIST_ERROR = 'POST_LIST_ERROR'
