export const API_AUTHOR_LIST = '/users'
export const API_AUTHOR_DETAIL = '/users/'
export const API_POST_LIST = '/posts'
export const API_POST_DETAIL = '/posts/'
export const API_COMMENT_LIST = '/comments'
