export const AUTHOR_DETAIL_REQUEST = 'AUTHOR_DETAIL_REQUEST'
export const AUTHOR_DETAIL_SUCCESS = 'AUTHOR_DETAIL_SUCCESS'
export const AUTHOR_DETAIL_ERROR = 'AUTHOR_DETAIL_ERROR'

export const POST_AUTHOR_REQUEST = 'POST_AUTHOR_REQUEST'
export const POST_AUTHOR_SUCCESS = 'POST_AUTHOR_SUCCESS'
export const POST_AUTHOR_ERROR = 'POST_AUTHOR_ERROR'
