export const POST_DETAIL_REQUEST = 'POST_DETAIL_REQUEST'
export const POST_DETAIL_SUCCESS = 'POST_DETAIL_SUCCESS'
export const POST_DETAIL_ERROR = 'POST_DETAIL_ERROR'

export const POST_COMMENT_LIST_REQUEST = 'POST_COMMENT_LIST_REQUEST'
export const POST_COMMENT_LIST_SUCCESS = 'POST_COMMENT_LIST_SUCCESS'
export const POST_COMMENT_LIST_ERROR = 'POST_COMMENT_LIST_ERROR'
